---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`imprimir`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`cambiarCartucho`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`agregarHojasA4`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`agregarHojasOficio`"
  checked: false
name: Sobrecarga
