---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: atender(Gato)
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: atender(Mascota)
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: atender(Perro)
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: atender
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: internar
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: internar(Gato, int)
  checked: true
name: Poniendo la firma
