---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: atender(Gato)
  checked: true
- value: atender(Mascota)
  checked: false
- value: atender(Perro)
  checked: true
- value: atender
  checked: false
- value: internar
  checked: false
- value: internar(Gato, int)
  checked: true
name: Poniendo la firma
